apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: chat-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-app-custom
  replicas: 1
  template:
    metadata:
      labels:
        app: chat-app
        app.kubernetes.io/name: chat-app-custom
    spec:
      containers:
      - name: chat
        image: chat:latest
        imagePullPolicy: Never
        stdin: true
        ports:
          - containerPort: 3001

