package edu.gla.kail.ad.core;

import com.google.cloud.Tuple;
import com.google.protobuf.Timestamp;
import edu.gla.kail.ad.Client.InputInteraction;
import edu.gla.kail.ad.Client.InteractionRequest;
import edu.gla.kail.ad.core.Log.RequestLog;
import edu.gla.kail.ad.core.Log.ResponseLog;
import edu.gla.kail.ad.core.Log.ResponseLog.Builder;
import edu.gla.kail.ad.core.Log.ResponseLog.MessageStatus;
import edu.gla.kail.ad.core.Log.ResponseLogOrBuilder;
import edu.gla.kail.ad.core.Log.Turn;
import edu.gla.kail.ad.core.Log.TurnOrBuilder;
import io.reactivex.Observable;
import io.reactivex.schedulers.Schedulers;

import java.io.IOException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * The manager is configured to have conversations with specified agents (of certain agent type,
 * * e.g. Dialogflow or Alexa).
 * Conversation management includes handling session state, including starting sessions (assigning
 * session IDs), as well as request identifiers. It also handles serialization of conversation log
 * data.
 * <p>
 * Instruction of usage:
 * 1) Set up the Dialog agents using setUpAgents method.
 * 2) Call the getResponseFromAgent for passed input.
 * 3)
 * TODO(Adam): further part needs to be implemented
 * <p>
 * Example usage :
 * DialogAgentManager dialogAgentManager = new DialogAgentManager();
 * dialogAgentManager.setUpAgents(_configurationTuples);
 * dialogAgentManager.getResponse(interactionRequest);
 **/

public class DialogAgentManager {
    // List of instances of used Dialog agents.
    private List<AgentInterface> _agents;
    // Session ID is a unique identifier of a session which is assigned by the method
    // startSession() called by DialogAgentManager constructor.
    private String _sessionId;
    private LogTurnManagerSingleton _logTurnManagerSingleton;

    /**
     * Create a unique session ID generated with startSession() method.
     */
    public DialogAgentManager() {
        startSession();
    }

    /**
     * Create a unique sessionId.
     */
    private void startSession() {
        _sessionId = generateRandomID();
        _logTurnManagerSingleton = LogTurnManagerSingleton.getLogTurnManagerSingleton();
    }

    /**
     * Called before the end of the session to store and configuration of the DialogAgentManager ??
     */
    public void endSession() {
        // TODO(Adam): Creation of configuration file - to be done later on.
    }

    /**
     * Creates random ID used for session ID and request ID.
     *
     * @return String - A random ID consisting of timestamp and a random id generated by UUID.
     */
    private String generateRandomID() {
        return (new java.sql.Timestamp(System.currentTimeMillis())).toString() + UUID.randomUUID
                ().toString();
    }

    /**
     * Set up (e.g. authenticate) all agents and store them to the list of agents.
     *
     * @param configurationTuples - The list stores the entities of ConfigurationTuple,
     *         which holds data required by each agent.
     * @throws IllegalArgumentException - Raised by _agents.add(new
     *         DialogflowAgent(_sessionId, agentSpecificData.get(0)));
     * @throws IOException, IllegalArgumentException
     */
    public void setUpAgents(List<ConfigurationTuple> configurationTuples) throws
            IllegalArgumentException, IOException {
        _agents = new ArrayList<>();
        for (ConfigurationTuple configurationTuple : configurationTuples) {
            switch (configurationTuple.get_agentType()) {
                case NOTSET:
                    break;
                case DIALOGFLOW:
                    List<Tuple> agentSpecificData = checkNotNull(configurationTuple
                            .get_agentSpecificData(), "The Dialogflow specific data is null!");
                    if (agentSpecificData.size() != 1) {
                        throw new IllegalArgumentException("The Dialogflow agent specific data " +
                                "passed is not valid for Dialogflow! It has to be project ID and " +
                                "Service Account key file directory.");
                    }
                    _agents.add(new DialogflowAgent(_sessionId, agentSpecificData.get(0)));
                    break;
                /*case DUMMYAGENT: // TODO(ADAM): Delete these agents after testing is done.
                Dummy agents have been moved to test folder.
                    _agents.add(new DummyAgent());
                    break;
                case FAILINGEXCEPTIONDUMMYAGENT:
                    _agents.add(new FailingExceptionDummyAgent());
                    break;
                case FAILINGNULLDUMMYAGENT:
                    _agents.add(new FailingNullDummyAgent());
                    break;
                case FAILINGTIMEDUMMYAGENT:
                    _agents.add(new FailingTimeDummyAgent());
                    break;*/
                default:
                    throw new IllegalArgumentException("The type of the agent provided " +
                            "\"" +
                            configurationTuple
                                    .get_agentType() + "\" is not currently supported " +
                            "(yet)!");
            }
        }
    }

    /**
     * Take the request from the service and send back chosen response.
     * Store the turn in the logfile
     *
     * @param interactionRequest - The request sent by the client.
     * @return ResponseLog - The response chosen with a particular method from the list of responses
     *         obtained by calling all the agents.
     */
    public ResponseLog getResponse(InteractionRequest interactionRequest) throws Exception {
        RequestLog requestLog = RequestLog.newBuilder()
                .setRequestId(generateRandomID())
                .setTime(getCurrentTimeStamp())
                .setClientId(interactionRequest.getClientId())
                .setInteraction(interactionRequest.getInteraction()).build();

        List<ResponseLog> responses = getResponsesFromAgents(interactionRequest.getInteraction());
        ResponseLog chosenResponse = chooseOneResponse(responses); // TODO(Jeff): This may throw
        // exception. Should I leave the error and propagate to higher levels, or do something here?
        TurnOrBuilder turnBuilder = Turn.newBuilder()
                .setRequestLog(requestLog)
                .setSessionId(_sessionId)
                .setResponseLog(chosenResponse);
        for (ResponseLog response : responses) {
            ((Turn.Builder) turnBuilder).addCandidateResponse(response);
        }
        Turn turn = ((Turn.Builder) turnBuilder).build();

        // Store the turn in the log file.
        _logTurnManagerSingleton.addTurn(turn);
        return chosenResponse;
    }

    /**
     * Get Request from Client and convert it to the RequestLog.
     * Return the list of responses for a given request.
     *
     * @param inputInteraction - The a data structure (implemented in log.proto) holding
     *         the interaction input passed to agents.
     * @return List<ResponseLog> - The list of responses of all agents set up on the
     *         setUpAgents(...) method call.
     */
    private List<ResponseLog> getResponsesFromAgents(InputInteraction inputInteraction) {
        if (checkNotNull(_agents, "Agents are not set up! Use the method" +
                " setUpAgents() first.").isEmpty()) {
            throw new IllegalArgumentException("The list of agents is empty!");
        }
        List<ResponseLog> listOfResponseLogs = asynchronousAgentCaller(inputInteraction);
        // TODO(Adam) Remove when the log saving is implemented. Currently we can see the output.
        listOfResponseLogs.forEach(System.out::println);
        return listOfResponseLogs;
    }

    /**
     * Return the responses by calling agents asynchronously.
     *
     * @param inputInteraction - The a data structure (implemented in log .proto) holding
     *         the interaction input sent to the agent.
     * @return List<ResponseLog> - The list of responses of all agents set up on the
     *         setUpAgents(...) method call.
     */
    private List<ResponseLog> asynchronousAgentCaller(InputInteraction inputInteraction) {
        Observable<AgentInterface> agentInterfaceObservable = Observable.fromIterable(_agents);
        return (agentInterfaceObservable.flatMap(agentObservable -> Observable
                .just(agentObservable)
                .subscribeOn(Schedulers.computation())
                .take(5, TimeUnit.SECONDS) // Take only the observable emitted (completed)
                // within specified time.
                .map(agent -> callForResponseAndValidate(agent, inputInteraction))
        ).toList().blockingGet());
    }

    /**
     * Return the responses by calling agents synchronously.
     *
     * @param inputInteraction - The a data structure (implemented in log .proto) holding
     *         the interaction input sent to the agent.
     * @return List<ResponseLog> - The list of responses of all agents set up on the
     *         setUpAgents(...) method call.
     */
    private List<ResponseLog> synchronousAgentCaller(InputInteraction inputInteraction) {
        List<ResponseLog> listOfResponseLogs = new ArrayList<>();
        for (AgentInterface agent : _agents) {
            listOfResponseLogs.add(callForResponseAndValidate(agent, inputInteraction));
        }
        return listOfResponseLogs;
    }

    /**
     * Return a valid response from an agent within a set time period or return and unsuccessful
     * response.
     *
     * @param agent - The agent which
     * @param inputInteraction - The a data structure (implemented in log .proto) holding
     *         the interaction input sent to the agent.
     * @return ResponseLog - Response from the agent or unsuccessful reponse.
     */
    private ResponseLog callForResponseAndValidate(AgentInterface agent, InputInteraction
            inputInteraction) {
        // TODO(Adam): Resend a call if unsuccessful? To be done later on.
        Callable<ResponseLog> callableCallForResponseAndValidate = () -> {
            try {
                return checkNotNull(agent.getResponseFromAgent(inputInteraction),
                        "The response from Agent was null!");
            } catch (Exception exception) {
                return ResponseLog.newBuilder()
                        .setMessageStatus(MessageStatus.UNSUCCESSFUL)
                        .setErrorMessage(exception.getMessage())
                        .setServiceProvider(agent.getServiceProvider())
                        .setTime(Timestamp.newBuilder()
                                .setSeconds(Instant.now()
                                        .getEpochSecond())
                                .setNanos(Instant.now()
                                        .getNano())
                                .build())
                        .build();
            }
        };

        ExecutorService executor = Executors.newSingleThreadExecutor();
        Future<ResponseLog> future = executor.submit(callableCallForResponseAndValidate);
        ResponseLog responseLog;
        try {
            responseLog = future.get(5, TimeUnit.SECONDS);
        } catch (Exception exception) {
            future.cancel(true); // Cancel and send a thread interrupt.
            ResponseLogOrBuilder responseLogBuilder = ResponseLog.newBuilder()
                    .setMessageStatus(MessageStatus.UNSUCCESSFUL)
                    .setServiceProvider(agent.getServiceProvider())
                    .setTime(getCurrentTimeStamp());
            if (exception.getMessage() == null) {
                ((Builder) responseLogBuilder).setErrorMessage(exception.toString());
            } else {
                ((Builder) responseLogBuilder).setErrorMessage(exception.getMessage());
            }
            responseLog = ((Builder) responseLogBuilder).build();
        } finally {
            executor.shutdownNow();
        }
        return responseLog;
    }


    /**
     * Choose the response from the list obtained from all the agents.
     *
     * @param responses - The list of ResponseLog responses obtained from agents.
     * @return ResponseLog - One of the responses chosen using specified ranking/choosing method.
     * @throws Exception - Throw when the list is not initialized or empty.
     */
    private ResponseLog chooseOneResponse(List<ResponseLog> responses) throws Exception {
        if (checkNotNull(responses, "The list passed to the chooseOneResponse function is not " +
                "initialized!").isEmpty()) {
            throw new IllegalArgumentException("The list of responses is empty!");
        }
        return chooseFirstValidResponse(responses);
    }

    /**
     * Choose the first successful response.
     *
     * @param responses - The list of ResponseLog responses obtained from agents.
     * @return ResponseLog - The first successful response or unsuccessful response if none of the
     *         provided responses were successful.
     */
    private ResponseLog chooseFirstValidResponse(List<ResponseLog> responses) {
        for (ResponseLog responseLog : responses) {
            if (responseLog.getMessageStatus() == MessageStatus.SUCCESSFUL) {
                return responseLog;
            }
        }
        return ResponseLog.newBuilder()
                .setMessageStatus(MessageStatus.UNSUCCESSFUL)
                .setErrorMessage("None of the passed responses had a successful call to the agent.")
                .setTime(getCurrentTimeStamp())
                .build();
    }

    private Timestamp getCurrentTimeStamp() {
        return Timestamp.newBuilder()
                .setSeconds(Instant.now()
                        .getEpochSecond())
                .setNanos(Instant.now()
                        .getNano())
                .build();
    }
}