package edu.gla.kail.ad.core;

/**
 * Reformat all the turns from a file generated by LogTurnManagerSingleton to separate files of
 * LogEntries for each session.
 */
public class LogEntryManager {

}
